name: Vercel Action
on:
  schedule:
    - cron: '*/5 18 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --frozen
      - run: yarn run build
      - run: yarn run deploy -c -t $VERCEL_TOKEN
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
